[workspace]
resolver = "2"
members = ["openapi"]

[package]
name = "eveonline-esi"
version = "0.1.0"
edition = "2024"
authors = ["ZeroDegress <zerodegress@outlook.com>"]
description = "EVE Online ESI for Rust."
license = "LGPL-3.0"

[dependencies]
eveonline_esi_openapi = { path = "./openapi" }
