/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity : Unprocessable entity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity {
    /// Unprocessable entity message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity {
    /// Unprocessable entity
    pub fn new() -> DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity {
        DeleteCharactersCharacterIdMailLabelsLabelIdUnprocessableEntity {
            error: None,
        }
    }
}

