/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetKillmailsKillmailIdKillmailHashUnprocessableEntity : Unprocessable entity
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetKillmailsKillmailIdKillmailHashUnprocessableEntity {
    /// Unprocessable entity message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl GetKillmailsKillmailIdKillmailHashUnprocessableEntity {
    /// Unprocessable entity
    pub fn new() -> GetKillmailsKillmailIdKillmailHashUnprocessableEntity {
        GetKillmailsKillmailIdKillmailHashUnprocessableEntity {
            error: None,
        }
    }
}

