/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetFleetsFleetIdWingsSquad : squad object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetFleetsFleetIdWingsSquad {
    /// id integer
    #[serde(rename = "id")]
    pub id: i64,
    /// name string
    #[serde(rename = "name")]
    pub name: String,
}

impl GetFleetsFleetIdWingsSquad {
    /// squad object
    pub fn new(id: i64, name: String) -> GetFleetsFleetIdWingsSquad {
        GetFleetsFleetIdWingsSquad {
            id,
            name,
        }
    }
}

