/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCharactersCharacterIdMailLabelsLabel : label object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdMailLabelsLabel {
    /// color string
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Color>,
    /// label_id integer
    #[serde(rename = "label_id", skip_serializing_if = "Option::is_none")]
    pub label_id: Option<i32>,
    /// name string
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// unread_count integer
    #[serde(rename = "unread_count", skip_serializing_if = "Option::is_none")]
    pub unread_count: Option<i32>,
}

impl GetCharactersCharacterIdMailLabelsLabel {
    /// label object
    pub fn new() -> GetCharactersCharacterIdMailLabelsLabel {
        GetCharactersCharacterIdMailLabelsLabel {
            color: None,
            label_id: None,
            name: None,
            unread_count: None,
        }
    }
}
/// color string
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Color {
    #[serde(rename = "#0000fe")]
    Hash0000fe,
    #[serde(rename = "#006634")]
    Hash006634,
    #[serde(rename = "#0099ff")]
    Hash0099ff,
    #[serde(rename = "#00ff33")]
    Hash00ff33,
    #[serde(rename = "#01ffff")]
    Hash01ffff,
    #[serde(rename = "#349800")]
    Hash349800,
    #[serde(rename = "#660066")]
    Hash660066,
    #[serde(rename = "#666666")]
    Hash666666,
    #[serde(rename = "#999999")]
    Hash999999,
    #[serde(rename = "#99ffff")]
    Hash99ffff,
    #[serde(rename = "#9a0000")]
    Hash9a0000,
    #[serde(rename = "#ccff9a")]
    HashCcff9a,
    #[serde(rename = "#e6e6e6")]
    HashE6e6e6,
    #[serde(rename = "#fe0000")]
    HashFe0000,
    #[serde(rename = "#ff6600")]
    HashFf6600,
    #[serde(rename = "#ffff01")]
    HashFfff01,
    #[serde(rename = "#ffffcd")]
    HashFfffcd,
    #[serde(rename = "#ffffff")]
    HashFfffff,
}

impl Default for Color {
    fn default() -> Color {
        Self::Hash0000fe
    }
}

