/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetCharactersCharacterIdPlanetsPlanetIdOk : 200 ok object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCharactersCharacterIdPlanetsPlanetIdOk {
    /// links array
    #[serde(rename = "links")]
    pub links: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdLink>,
    /// pins array
    #[serde(rename = "pins")]
    pub pins: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdPin>,
    /// routes array
    #[serde(rename = "routes")]
    pub routes: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdRoute>,
}

impl GetCharactersCharacterIdPlanetsPlanetIdOk {
    /// 200 ok object
    pub fn new(links: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdLink>, pins: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdPin>, routes: Vec<models::GetCharactersCharacterIdPlanetsPlanetIdRoute>) -> GetCharactersCharacterIdPlanetsPlanetIdOk {
        GetCharactersCharacterIdPlanetsPlanetIdOk {
            links,
            pins,
            routes,
        }
    }
}

