/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetUniverseAsteroidBeltsAsteroidBeltIdOk : 200 ok object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUniverseAsteroidBeltsAsteroidBeltIdOk {
    /// name string
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "position")]
    pub position: Box<models::GetUniverseAsteroidBeltsAsteroidBeltIdPosition>,
    /// The solar system this asteroid belt is in
    #[serde(rename = "system_id")]
    pub system_id: i32,
}

impl GetUniverseAsteroidBeltsAsteroidBeltIdOk {
    /// 200 ok object
    pub fn new(name: String, position: models::GetUniverseAsteroidBeltsAsteroidBeltIdPosition, system_id: i32) -> GetUniverseAsteroidBeltsAsteroidBeltIdOk {
        GetUniverseAsteroidBeltsAsteroidBeltIdOk {
            name,
            position: Box::new(position),
            system_id,
        }
    }
}

