/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostCharactersCharacterIdMailLabelsLabel : label object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCharactersCharacterIdMailLabelsLabel {
    /// Hexadecimal string representing label color, in RGB format
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<Color>,
    /// name string
    #[serde(rename = "name")]
    pub name: String,
}

impl PostCharactersCharacterIdMailLabelsLabel {
    /// label object
    pub fn new(name: String) -> PostCharactersCharacterIdMailLabelsLabel {
        PostCharactersCharacterIdMailLabelsLabel {
            color: None,
            name,
        }
    }
}
/// Hexadecimal string representing label color, in RGB format
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Color {
    #[serde(rename = "#0000fe")]
    Hash0000fe,
    #[serde(rename = "#006634")]
    Hash006634,
    #[serde(rename = "#0099ff")]
    Hash0099ff,
    #[serde(rename = "#00ff33")]
    Hash00ff33,
    #[serde(rename = "#01ffff")]
    Hash01ffff,
    #[serde(rename = "#349800")]
    Hash349800,
    #[serde(rename = "#660066")]
    Hash660066,
    #[serde(rename = "#666666")]
    Hash666666,
    #[serde(rename = "#999999")]
    Hash999999,
    #[serde(rename = "#99ffff")]
    Hash99ffff,
    #[serde(rename = "#9a0000")]
    Hash9a0000,
    #[serde(rename = "#ccff9a")]
    HashCcff9a,
    #[serde(rename = "#e6e6e6")]
    HashE6e6e6,
    #[serde(rename = "#fe0000")]
    HashFe0000,
    #[serde(rename = "#ff6600")]
    HashFf6600,
    #[serde(rename = "#ffff01")]
    HashFfff01,
    #[serde(rename = "#ffffcd")]
    HashFfffcd,
    #[serde(rename = "#ffffff")]
    HashFfffff,
}

impl Default for Color {
    fn default() -> Color {
        Self::Hash0000fe
    }
}

