/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PostCharactersCharacterIdFittingsCreated : 201 created object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PostCharactersCharacterIdFittingsCreated {
    /// fitting_id integer
    #[serde(rename = "fitting_id")]
    pub fitting_id: i32,
}

impl PostCharactersCharacterIdFittingsCreated {
    /// 201 created object
    pub fn new(fitting_id: i32) -> PostCharactersCharacterIdFittingsCreated {
        PostCharactersCharacterIdFittingsCreated {
            fitting_id,
        }
    }
}

