/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutFleetsFleetIdMembersMemberIdUnprocessableEntity : 422 unprocessable entity object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutFleetsFleetIdMembersMemberIdUnprocessableEntity {
    /// error message
    #[serde(rename = "error", skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

impl PutFleetsFleetIdMembersMemberIdUnprocessableEntity {
    /// 422 unprocessable entity object
    pub fn new() -> PutFleetsFleetIdMembersMemberIdUnprocessableEntity {
        PutFleetsFleetIdMembersMemberIdUnprocessableEntity {
            error: None,
        }
    }
}

