/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutCharactersCharacterIdMailMailIdContents : contents object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutCharactersCharacterIdMailMailIdContents {
    /// Labels to assign to the mail. Pre-existing labels are unassigned.
    #[serde(rename = "labels", skip_serializing_if = "Option::is_none")]
    pub labels: Option<Vec<i32>>,
    /// Whether the mail is flagged as read
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<bool>,
}

impl PutCharactersCharacterIdMailMailIdContents {
    /// contents object
    pub fn new() -> PutCharactersCharacterIdMailMailIdContents {
        PutCharactersCharacterIdMailMailIdContents {
            labels: None,
            read: None,
        }
    }
}

