/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PutFleetsFleetIdWingsWingIdNaming : naming object
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PutFleetsFleetIdWingsWingIdNaming {
    /// name string
    #[serde(rename = "name")]
    pub name: String,
}

impl PutFleetsFleetIdWingsWingIdNaming {
    /// naming object
    pub fn new(name: String) -> PutFleetsFleetIdWingsWingIdNaming {
        PutFleetsFleetIdWingsWingIdNaming {
            name,
        }
    }
}

