/*
 * EVE Swagger Interface
 *
 * An OpenAPI for EVE Online
 *
 * The version of the OpenAPI document: 1.33
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ServiceUnavailable : Service unavailable model
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ServiceUnavailable {
    /// Service unavailable message
    #[serde(rename = "error")]
    pub error: String,
}

impl ServiceUnavailable {
    /// Service unavailable model
    pub fn new(error: String) -> ServiceUnavailable {
        ServiceUnavailable {
            error,
        }
    }
}

